// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zxilFBvs5JxZN5EM9zCF_k32qfOU-_o',
    appId: '1:1034781931388:web:66c2ad87a98332e6c016f9',
    messagingSenderId: '1034781931388',
    projectId: 'flutter-app-c34f4',
    authDomain: 'flutter-app-c34f4.firebaseapp.com',
    databaseURL: 'https://flutter-app-c34f4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c34f4.appspot.com',
    measurementId: 'G-3HCGL5EJZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQU1vbi-ZWQKQBPZm6N3sRaOIga9le8E',
    appId: '1:1034781931388:android:30013781fa265cefc016f9',
    messagingSenderId: '1034781931388',
    projectId: 'flutter-app-c34f4',
    databaseURL: 'https://flutter-app-c34f4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c34f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3SSWXoKDcJSw9ef4hpj9EAArEXJh6eU',
    appId: '1:1034781931388:ios:a8a04cb9e74cd65ac016f9',
    messagingSenderId: '1034781931388',
    projectId: 'flutter-app-c34f4',
    databaseURL: 'https://flutter-app-c34f4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c34f4.appspot.com',
    iosBundleId: 'com.example.learnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3SSWXoKDcJSw9ef4hpj9EAArEXJh6eU',
    appId: '1:1034781931388:ios:295689120b19c83ac016f9',
    messagingSenderId: '1034781931388',
    projectId: 'flutter-app-c34f4',
    databaseURL: 'https://flutter-app-c34f4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c34f4.appspot.com',
    iosBundleId: 'com.example.learnApp.RunnerTests',
  );
}
